### ISSUE TITLE
Publicação de JS

### ISSUE THREAD

**Issue by hernandev** [artesaos/moip#1]
Os assets javascript, por se tratarem de uma solução de pagamentos não deveriam ser disponibilizadas ou sequer encorajadas.

O melhor caminho é incluir o javascript diretamente do gateway.

Cenário: o gateway detecta uma falha de segurança e lança uma correção da biblioteca javascript. Isso irá tornar cada usuario do pacote um cliente do gateway sucetivel a fraude/danos.

Claro que a decisão é de cada um, mas isso deveria ser explicitamente setado pelo usuario, claro, estando ciente dos riscos envolvidos.

Sugestão: Forneça um helper para as views que injete o <script> diretamente para o js no gateway de pagamentos.

**Comment by SOSTheBlack** [comment]
@hernandev demorei para me posicionar pois esse package é um tanto que antigo e tive que dar uma relida para entender como funciona hoje, e se é possível implementar a medida de segurança que você sugeriu.

O fluxo em que o package trabalha hoje é do modo e do método que o Moip sugeri, pois é somente seguinte esse método que o moip homologa a sua aplicação. Mas sinceramente eu não sei se for desenvolvido um helper e solicitar a homologação para o Moip eles irão barrar.

Irei entrar em contato com desenvolvimento para saber se o mesmo pode ser feito. Creio que eles irão demorar um pouco para responder sobre algo da API v1 já que a v2 está preste a sair, então esse issuii ficará no backlog

Voltando a sua sugestão de segurança, pelo o que eu entendi o script js [desse arquivo](https://github.com/artesaos/moip/blob/v1/src/views/moip.blade.php) se tornaria um helpr, seria isso?

**Comment by hernandev** [comment]
a ideia é incluir o script direto do site do moip, ao inves de fornece-lo com o pacote

veja como funciona no stripe:

```
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
```

Veja que o arquivo é carregado diretamente do site do stripe, e não de dentro do pacote. dessa forma, se houver alguma falha de segurança que for corrigida pelo stripe (no caso o moip) a mudança ira ser refletida instantaneamente nos clientes.

Publicar o js junto com o pacote, iria demandar um update no pacote e um update na instalação do cliente, e alguns clientes poderiam ficar meses rodando com uma versõa insegura.

Conseguiu entender o ponto?

**Comment by hernandev** [comment]
Olha só, na documentação do moip, também fornecem o link direto:

```
<script
type='text/javascript'
src='https://desenvolvedor.moip.com.br/sandbox/transparente/MoipWidget-v2.js'
charset='ISO-8859-1'>
</script>
```

**Comment by SOSTheBlack** [comment]
Entendi agora o que você quis dizer!

A forma como você citou no seu segundo comentário dando exemplo da documentação é exatamente como eu faço. O que é publicado pelo package é apenas são apenas arquivos jquery como você pode conferir [aqui](https://github.com/artesaos/moip/tree/v1/public)

A linha 5 do arquivo [moip.blade.php](https://github.com/artesaos/moip/blob/v1/src/views/moip.blade.php#L5) contem uma variável que carrega o link do stripe

No arquivo [MoipController.php](https://github.com/artesaos/moip/blob/v1/src/controllers/MoipController.php#L112) na function environment eu defino qual o valor dessa variável

**Comment by hernandev** [comment]
a show @SOSTheBlack só pra garantir, não havia visto o code, vlw
