### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $token ]] in class Moip\MoipBasicAuth

### ISSUE THREAD

**Issue by jorgedjr21** [artesaos/moip#18]
Estou recebendo esse erro, após atualizar minha aplicação com o Laravel 5.4.

**Comment by felipeneuhauss** [comment]
Eu também.

**Comment by SOSTheBlack** [comment]
podem postar trecho do código que está retornando esse erro ?

**Comment by ghost** [comment]
@jorgedjr21 Suas configurações de credenciais `MOIP_KEY` e `MOIP_TOKEN` estão presentes no .env?

**Comment by jorgedjr21** [comment]
@gilberto-bueno estão sim.

**Comment by ghost** [comment]
Encontrei o problema, estou fazendo um fork e vou mandar um PR.

**Comment by SOSTheBlack** [comment]
Eu já havia corrigido isso ontem de noite, porém não subi pois estava em testes.
acabei de dar o push.
Façam os testes vocês mesmo para fixar, e de um feedback.

```php
try {
    $customer = Moip::customers()->setOwnId(uniqid())
        ->setFullname('Fulano de Tal')
        ->setEmail('fulano@email.com')
        ->setBirthDate('1988-12-30')
        ->setTaxDocument('22222222222')
        ->setPhone(11, 66778899)
        ->addAddress('BILLING',
            'Rua de teste', 123,
            'Bairro', 'Sao Paulo', 'SP',
            '01234567', 8)
        ->addAddress('SHIPPING',
            'Rua de teste do SHIPPING', 123,
            'Bairro do SHIPPING', 'Sao Paulo', 'SP',
            '01234567', 8)
        ->create();
    dd($customer);
} catch (Exception $e) {
    dd($e->__toString());
}
```

PS: coloque dev no require do seu projeto.

**Comment by ghost** [comment]
O problema está relacionado ao `make`:
https://github.com/laravel/framework/issues/17556

**Comment by SOSTheBlack** [comment]
Sim, eu detectei isso também. nem o make ou o makeWith está funcionando como deveria.
utilizei o new 
https://github.com/artesaos/moip/blob/master/src/Providers/MoipServiceProvider.php

**Comment by ghost** [comment]
Legal.
Eu deixei assim:

```php
public function start()
{
    $token = config('artesaos.moip.credentials.token');
    $key = config('artesaos.moip.credentials.key');
        
    $moipAuthentication = new MoipBasicAuth($token, $key);
    $this->moip = new Api($moipAuthentication, $this->getHomologated()); 
    
    return $this;
}
```

**Comment by SOSTheBlack** [comment]
Legal, já achamos o problema, irei fechar o issue.
