### ISSUE TITLE
Compatibilidade com Lumen 5.4

### ISSUE THREAD

**Issue by SOSTheBlack** [artesaos/moip#21]
Testar compatibilidade com Lumen 5.4!

**Comment by SOSTheBlack** [comment]
@meneguite Então, eu não tentei a compatibilidade do package com o Lumen 5.4.
Se você poder fazer esse teste e nos da um feedback aqui ficaria grato.

PS: Faz o teste com a versão dev do package, pois a ultima versão estável, não é compatível nem com Laravel 5.4

**Comment by meneguite** [comment]
Blz vou fazer um teste aqui.. já te dou um feedback..

**Comment by meneguite** [comment]
@SOSTheBlack de inicio já peguei um problema que a versão mais nova não possue o helper config_path.. uma forma de resolver esse problema seria trocando de config_path('/artesaos/moip.php') para base_path('config/artesaos/moip.php') mas precisamos ver isso com calma pois quem usa um path customizado vai quebrar..

**Comment by meneguite** [comment]
Se bem que, o lumen não tem o vendor publish, talvez apenas verificar se é ou não o lumen e nem passar por essa base de código..

**Comment by meneguite** [comment]
Talvez isso resolva: 
```php
if (function_exists('config_path')) {
            $this->publishes([__DIR__.'/../../config/moip.php' => config_path('/artesaos/moip.php')], 'config');
            $this->mergeConfigFrom(__DIR__.'/../../config/moip.php', config_path('/artesaos/moip.php', 'config'));
        }
```php

**Comment by SOSTheBlack** [comment]
@meneguite Acredito que você não esteja com o commit mais atual da versão dev.

Eu fiz um verificação, para saber se o app é lumen,
De uma olhada nessas duas linhas
https://github.com/artesaos/moip/blob/master/src/Providers/MoipServiceProvider.php#L56
https://github.com/artesaos/moip/blob/master/src/Providers/MoipServiceProvider.php#L71

Eu cheguei a fazer essas verificações, só o que eu me lembro bem, testei apenas em lumen 5.2.

**Comment by meneguite** [comment]
Hum verdade estava usando o master do fork que fiz.. mas já fez alguns commits depois disso.. vou atualizar aqui..

**Comment by meneguite** [comment]
Bom aparentemente agora está funcionando sim... tenho que aguardar o cliente agora para que ele possa me disponibilizar as KEY para testar certinho.. mas ele já está fazendo as requisições e retornando o erro como deveria.. :) vlw ai pela atenção e precisando é só chamar o/

**Comment by SOSTheBlack** [comment]
@meneguite você pode utilizar o ambiente de teste, o MoIP disponibiliza token and key para vc testar rapidamente.

As credenciais padrões se encontra no arquivo de configuração, se vc não definiar nada no seu `.env` será utilizada elas.
https://github.com/artesaos/moip/blob/master/config/moip.php

Sinta-se a vontade para testar

Obrigado pela contribuições com o package.

**Comment by meneguite** [comment]
Salvou minha noite.. :) já testei e funcionou perfeitamente.. muito obrigado!
