### ISSUE TITLE
Pasta com nome "facade"

### ISSUE THREAD

**Issue by lucassena** [artesaos/moip#22]
Olá, estou tendo problemas recentes com `Class 'Artesaos\Moip\Facades\Moip' not found`; na instrução `$moip = \Moip::start();`.

Acontece que o nome do diretório está "facade" e não "Facade", iso não pode gerar erro?

Abs

**Comment by cenoura** [comment]
Fixed on PR #23

**Comment by SOSTheBlack** [comment]
PR #23 Aceito

**Comment by raank** [comment]
O erro ainda persiste, sendo que baixei com `composer require artesaos/moip`, Laravel 5.4

**Comment by SOSTheBlack** [comment]
@raank qual versão do package está utilizando?

**Comment by raank** [comment]
`"artesaos/moip": "^1.0"`

**Comment by raank** [comment]
Uma solução temporária é usar o `composer require artesaos/moip:master`
