### ISSUE TITLE
O que aconteceu com este merge? (Sobre accounts)

### ISSUE THREAD

**Issue by lucassena** [artesaos/moip#24]
Olá, eu tinha feito um PR há um tempo que já tinha sido aprovado.

Mas o código referente a ele sumiu do _master_: https://github.com/artesaos/moip/commit/95869d22fb2b3e147d0e778b1e41985a17122e50

Eu lembro que o código estava no `src/Moip.php`, o que aconteceu?

Vi que ele foi retirado no commit: https://github.com/artesaos/moip/commit/ebf16d65ceac828098df5697900d9df31fae79dd

Abraços!

**Comment by SOSTheBlack** [comment]
Olá @lucassena, boa tarde!
Do modo que estava o package não estava rodando no Laravel 5.4.
Está enfrentando algum problema ?

**Comment by lucassena** [comment]
Sim, @SOSTheBlack, estou tendo problemas!

Estou precisando acessar o resource Account (referente à Conta Moip via API) da Moip. Por isso tinha feito aquele Pull Request anteriormente.

Por enquanto resolvi com meu Fork, só queria entender por que foi retirado e, talvez corrigir e dar um PR novamente sobre isso.

_Sobre o "Criar Conta Moip" na documentação: https://dev.moip.com.br/v2.0/reference#contas-moip_

**Comment by SOSTheBlack** [comment]
@lucassena pode resolver e dar um PR, sem problemas, apenas se certifique que será compativel com o Laravel 5.4

**Comment by lucassena** [comment]
Ok, vou fazer isso! Valeuu!!!
