### ISSUE TITLE
Falha no método populate da classe Resource\Customer

### ISSUE THREAD

**Issue by juniorjc** [artesaos/moip#33]
Parece que recentemente o Moip não está mais retornando os dados "taxDocument": { "number": "", "type": "" } e com isso a versão **1.3.1** do **moip/moip-sdk-php** não faz o tratamento no método populate da classe **Resource\Customer**. Como podemos fazer para atualizar a versão do moip/moip-sdk-php para a versão **2.1.0**, que já tem o tratamento?

Erro gerado atualmente.
_Undefined property: stdClass::$taxDocument at /app/vendor/moip/moip-sdk-php/src/Resource/Customer.php:261_

**Comment by dexfs** [comment]
@juniorjc se é só questão de atualizar a versão,  tu poderia fazer um fork e alterar no composer a versão do moip e enviar um pull request.

**Comment by juniorjc** [comment]
@dexfs vou fazer isso. Obrigado!
