### ISSUE TITLE
Error on loading class

### ISSUE THREAD

**Issue by esprajwol** [artesaos/moip#9]
Class Artesaos\Moip\Providers\MoipServiceProvider::class not found on Laravel 5.2

**Comment by SOSTheBlack** [comment]
Olá @esprajwol 
Ainda hoje irei verificar o erro e corrigir se o mesmo existir.

**Comment by voope** [comment]
eu tambem nao estou conseguindo instalar o pacote na versao 5.2.

**Comment by SOSTheBlack** [comment]
@esprajwol @voope 
Suporte ao Laravel 5.2.\* adicionado na [v1.0.1](https://github.com/artesaos/moip/releases/tag/v1.0.1)

Basta adicionarem em seu require

``` php
"artesaos/moip": "^1.0"
```

testem e de um feedback.

**Comment by paulojp-dev** [comment]
Estou com o mesmo problema no Laravel 5.4, mesmo executando com a referência "artesaos/moip": "^1.0" não é encontrado dentro do projeto o ServiceProvider da lib.
